export const TOGGLE_THEME = 'TOGGLE_THEME';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const OPEN_PROMPT = 'OPEN_PROMPT';
export const CLOSE_PROMPT = 'CLOSE_PROMPT';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const RESET_APP_STATE = 'RESET_APP_STATE';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SET_SETTINGS_SECTION = 'SET_SETTINGS_SECTION';

export const SET_LOADING_LOGIN = 'SET_LOADING_LOGIN';
export const SET_LOADING_LOGOUT = 'SET_LOADING_LOGOUT';
export const SET_LOADING_PAGE = 'SET_LOADING_PAGE';
export const SET_LOADING_DASHBOARD = 'SET_LOADING_DASHBOARD';
export const SET_LOADING_TRANSACTIONS = 'SET_LOADING_TRANSACTIONS';
export const SET_LOADING_SETTINGS_ADD = 'SET_LOADING_SETTINGS_ADD';
export const SET_LOADING_SETTINGS_DELETE = 'SET_LOADING_SETTINGS_DELETE';
export const SET_LOADING_TRANSACTIONS_DELETE = 'SET_LOADING_TRANSACTIONS_DELETE';
