export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SET_BILL = 'SET_BILL';
export const SET_PICKED_TIME_OPTION = 'SET_PICKED_TIME_OPTION';
export const SET_PICKED_TIME_INDEX = 'SET_PICKED_TIME_INDEX';
export const SET_PICKED_CURRENT_TIME = 'SET_PICKED_CURRENT_TIME';
export const RESET_TRANSACTION_STATE = 'RESET_TRANSACTION_STATE';
export const SET_PICKED_TIME_DATE = 'SET_PICKED_TIME_DATE';
export const SET_SORT_METHOD = 'SET_SORT_METHOD';
